<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"员工管理",
			            "menuJump":"列表",
			            "tableName":"yuangong"
			        }
			    ],
			    "menu":"员工管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"骑手管理",
			            "menuJump":"列表",
			            "tableName":"qishou"
			        }
			    ],
			    "menu":"骑手管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品信息管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品信息评价管理",
                        "menuJump":"列表",
                        "tableName":"goodsCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
							"报表",
                            "订单",
                            "删除"
                        ],
                        "menu":"商品信息订单管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrder"
                    }
                ],
                "menu":"商品信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"骑手接单管理",
			            "menuJump":"列表",
			            "tableName":"qishouJiedan"
			        }
			    ],
			    "menu":"骑手接单管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"商品类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryGoods"
			        }
			        ,
			        {
			            "buttons":[
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
							"回复",
			                "删除"
			            ],
			            "menu":"客服聊天管理",
			            "menuJump":"列表",
			            "tableName":"chat"
			        }
			    ],
			    "menu":"客服聊天管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图信息"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"商品信息管理",
	                    "menuJump":"列表",
	                    "tableName":"goods"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "修改"
	                    ],
	                    "menu":"商品信息评价管理",
	                    "menuJump":"列表",
	                    "tableName":"goodsCommentback"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "订单",
							"报表",
	                        "删除"
	                    ],
	                    "menu":"商品信息订单管理",
	                    "menuJump":"列表",
	                    "tableName":"goodsOrder"
	                }
	            ],
	            "menu":"商品信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"骑手接单管理",
			            "menuJump":"列表",
			            "tableName":"qishouJiedan"
			        }
			    ],
			    "menu":"骑手接单管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"新闻信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
							"回复",
			                "删除"
			            ],
			            "menu":"客服聊天管理",
			            "menuJump":"列表",
			            "tableName":"chat"
			        }
			    ],
			    "menu":"客服聊天管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"员工",
	    "tableName":"yuangong"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "接单"
	                    ],
	                    "menu":"可接订单",
	                    "menuJump":"列表",
	                    "tableName":"goodsOrder"
	                }
	            ],
	            "menu":"商品订单管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"我的接单",
			            "menuJump":"列表",
			            "tableName":"qishouJiedan"
			        }
			    ],
			    "menu":"我的接单管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"新闻信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻信息管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"骑手",
	    "tableName":"qishou"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"商品信息管理",
	                    "menuJump":"列表",
	                    "tableName":"goods"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"商品信息评价管理",
	                    "menuJump":"列表",
	                    "tableName":"goodsCommentback"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "订单"
	                    ],
	                    "menu":"商品信息订单管理",
	                    "menuJump":"列表",
	                    "tableName":"goodsOrder"
	                }
	            ],
	            "menu":"商品信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"骑手接单管理",
			            "menuJump":"列表",
			            "tableName":"qishouJiedan"
			        }
			    ],
			    "menu":"骑手接单管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"新闻信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"新闻信息管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
